import { UserDTO, TicketDTO } from './types';
import { calculateSlaDeadline } from './sla';

export const INITIAL_USERS: UserDTO[] = [
  {
    id: 'usr-citizen-1',
    name: 'Alex Chen',
    email: 'alex.chen@university.edu',
    role: 'CITIZEN',
    department: 'Computer Science',
    phone: '+1 (555) 234-5678',
  },
  {
    id: 'usr-staff-1',
    name: 'Marcus Vance',
    email: 'marcus.vance@facility.com',
    role: 'STAFF',
    department: 'Electrical',
    phone: '+1 (555) 876-5432',
  },
  {
    id: 'usr-staff-2',
    name: 'David Miller',
    email: 'david.miller@facility.com',
    role: 'STAFF',
    department: 'HVAC',
    phone: '+1 (555) 345-6789',
  },
  {
    id: 'usr-staff-3',
    name: 'Elena Rostova',
    email: 'elena.rostova@facility.com',
    role: 'STAFF',
    department: 'Plumbing',
    phone: '+1 (555) 987-6543',
  },
  {
    id: 'usr-admin-1',
    name: 'Sarah Connor',
    email: 'sarah.connor@facility.com',
    role: 'ADMIN',
    department: 'Operations Center',
    phone: '+1 (555) 111-2233',
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600 * 1000);

export const INITIAL_TICKETS: TicketDTO[] = [
  {
    id: 'tkt-1001',
    ticketCode: 'FF-1001',
    title: 'Main HVAC Chiller Failure - Science Block B',
    description: 'Chiller unit #3 high pressure trip. Temperature in chemistry laboratories exceeding safe limits (28°C). Urgent repair needed.',
    category: 'HVAC',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    building: 'Science Block B',
    floor: 'Floor 3',
    room: 'Lab 302',
    photoUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=60',
    reportedById: 'usr-citizen-1',
    reportedBy: INITIAL_USERS[0],
    assignedToId: 'usr-staff-2',
    assignedTo: INITIAL_USERS[2],
    slaDeadline: new Date(now.getTime() - 1 * 3600 * 1000).toISOString(), // Breached by 1h
    createdAt: hoursAgo(6).toISOString(),
    updatedAt: hoursAgo(2).toISOString(),
    history: [
      {
        id: 'hst-1',
        ticketId: 'tkt-1001',
        action: 'STATUS_CHANGE',
        fromStatus: null,
        toStatus: 'REPORTED',
        changedById: 'usr-citizen-1',
        changedBy: INITIAL_USERS[0],
        note: 'Ticket logged by Alex Chen',
        timestamp: hoursAgo(6).toISOString(),
      },
      {
        id: 'hst-2',
        ticketId: 'tkt-1001',
        action: 'ASSIGNED',
        fromStatus: 'REPORTED',
        toStatus: 'ASSIGNED',
        changedById: 'usr-admin-1',
        changedBy: INITIAL_USERS[4],
        note: 'Assigned to HVAC specialist David Miller',
        timestamp: hoursAgo(5).toISOString(),
      },
      {
        id: 'hst-3',
        ticketId: 'tkt-1001',
        action: 'STATUS_CHANGE',
        fromStatus: 'ASSIGNED',
        toStatus: 'IN_PROGRESS',
        changedById: 'usr-staff-2',
        changedBy: INITIAL_USERS[2],
        note: 'Dispatched to rooftop unit with thermal sensors',
        timestamp: hoursAgo(2).toISOString(),
      },
    ],
    comments: [
      {
        id: 'cmt-1',
        ticketId: 'tkt-1001',
        authorId: 'usr-staff-2',
        author: INITIAL_USERS[2],
        message: 'Replaced pressure switch. Re-balancing coolant flow now.',
        isInternal: true,
        createdAt: hoursAgo(1).toISOString(),
      }
    ]
  },
  {
    id: 'tkt-1002',
    ticketCode: 'FF-1002',
    title: 'Main Distribution Substation Breaker Tripped',
    description: 'Tech Tower West Wing lost primary 3-phase power. Emergency lights activated. Server racks on UPS backup power.',
    category: 'ELECTRICAL',
    priority: 'CRITICAL',
    status: 'REPORTED',
    building: 'Tech Tower West',
    floor: 'Basement 1',
    room: 'Substation Room B-04',
    photoUrl: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?w=600&auto=format&fit=crop&q=60',
    reportedById: 'usr-citizen-1',
    reportedBy: INITIAL_USERS[0],
    assignedToId: null,
    assignedTo: null,
    slaDeadline: calculateSlaDeadline('CRITICAL', hoursAgo(0.5)).toISOString(),
    createdAt: hoursAgo(0.5).toISOString(),
    updatedAt: hoursAgo(0.5).toISOString(),
    history: [
      {
        id: 'hst-4',
        ticketId: 'tkt-1002',
        action: 'STATUS_CHANGE',
        fromStatus: null,
        toStatus: 'REPORTED',
        changedById: 'usr-citizen-1',
        changedBy: INITIAL_USERS[0],
        note: 'Critical emergency ticket logged',
        timestamp: hoursAgo(0.5).toISOString(),
      }
    ],
    comments: []
  },
  {
    id: 'tkt-1003',
    ticketCode: 'FF-1003',
    title: 'Burst Water Pipe under Restroom Sink',
    description: 'Major water leakage spilling into corridor hallway. Isolation valve needs shutoff and pipe replacement.',
    category: 'PLUMBING',
    priority: 'HIGH',
    status: 'RESOLVED',
    building: 'Student Center',
    floor: 'Floor 1',
    room: 'Restroom 104',
    photoUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&auto=format&fit=crop&q=60',
    resolutionProofUrl: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=600&auto=format&fit=crop&q=60',
    reportedById: 'usr-citizen-1',
    reportedBy: INITIAL_USERS[0],
    assignedToId: 'usr-staff-3',
    assignedTo: INITIAL_USERS[3],
    slaDeadline: calculateSlaDeadline('HIGH', hoursAgo(8)).toISOString(),
    resolvedAt: hoursAgo(1).toISOString(),
    createdAt: hoursAgo(8).toISOString(),
    updatedAt: hoursAgo(1).toISOString(),
    history: [
      {
        id: 'hst-5',
        ticketId: 'tkt-1003',
        action: 'STATUS_CHANGE',
        fromStatus: 'IN_PROGRESS',
        toStatus: 'RESOLVED',
        changedById: 'usr-staff-3',
        changedBy: INITIAL_USERS[3],
        note: 'Isolated valve, replaced copper coupling line, and dried area floor.',
        timestamp: hoursAgo(1).toISOString(),
      }
    ],
    comments: [
      {
        id: 'cmt-2',
        ticketId: 'tkt-1003',
        authorId: 'usr-staff-3',
        author: INITIAL_USERS[3],
        message: 'New brass valve fitting installed. No further leak detected after 30min pressure test.',
        isInternal: false,
        createdAt: hoursAgo(1).toISOString(),
      }
    ]
  },
  {
    id: 'tkt-1004',
    ticketCode: 'FF-1004',
    title: 'Core Switch Fiber Link Intermittent Drops',
    description: 'Network rack in Engineering Building experiencing 45% packet loss on uplink fiber SFP+ module.',
    category: 'NETWORK',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    building: 'Engineering Complex',
    floor: 'Floor 2',
    room: 'Comm Closet 208',
    photoUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&auto=format&fit=crop&q=60',
    reportedById: 'usr-citizen-1',
    reportedBy: INITIAL_USERS[0],
    assignedToId: 'usr-staff-1',
    assignedTo: INITIAL_USERS[1],
    slaDeadline: calculateSlaDeadline('HIGH', hoursAgo(4)).toISOString(),
    createdAt: hoursAgo(4).toISOString(),
    updatedAt: hoursAgo(1.5).toISOString(),
    history: [],
    comments: []
  },
  {
    id: 'tkt-1005',
    ticketCode: 'FF-1005',
    title: 'Flickering Overhead LED Panel Lights',
    description: 'Fluorescent fixture buzzing loudly and flickering violently, causing headache during lecture.',
    category: 'ELECTRICAL',
    priority: 'LOW',
    status: 'CLOSED',
    building: 'Administrative Bldg',
    floor: 'Floor 3',
    room: 'Conference Room 305',
    photoUrl: null,
    resolutionProofUrl: 'https://images.unsplash.com/photo-1517999186661-ac0f0aef3699?w=600&auto=format&fit=crop&q=60',
    reportedById: 'usr-citizen-1',
    reportedBy: INITIAL_USERS[0],
    assignedToId: 'usr-staff-1',
    assignedTo: INITIAL_USERS[1],
    slaDeadline: calculateSlaDeadline('LOW', hoursAgo(30)).toISOString(),
    resolvedAt: hoursAgo(10).toISOString(),
    rating: 5,
    feedback: 'Super fast replacement! Technician Marcus Vance was polite and thorough.',
    createdAt: hoursAgo(30).toISOString(),
    updatedAt: hoursAgo(5).toISOString(),
    history: [],
    comments: []
  },
  {
    id: 'tkt-1006',
    ticketCode: 'FF-1006',
    title: 'Lab Door Electronic Lock Failure',
    description: 'RFID door access badge reader failing to grant access to authorized researchers. Solenoid stuck closed.',
    category: 'CARPENTRY',
    priority: 'MEDIUM',
    status: 'ASSIGNED',
    building: 'Innovation Hub',
    floor: 'Floor 1',
    room: 'Robotics Lab 102',
    photoUrl: null,
    reportedById: 'usr-citizen-1',
    reportedBy: INITIAL_USERS[0],
    assignedToId: 'usr-staff-1',
    assignedTo: INITIAL_USERS[1],
    slaDeadline: calculateSlaDeadline('MEDIUM', hoursAgo(2)).toISOString(),
    createdAt: hoursAgo(2).toISOString(),
    updatedAt: hoursAgo(1).toISOString(),
    history: [],
    comments: []
  }
];
